from dataclasses import dataclass, field
from textual.geometry import Offset
from typing import List, Set
from tofu_byte.tools.tools import Direction


@dataclass
class Scenario:
    name: str
    description: str
    objects_data: List[dict]
    player_start: Offset
    timeline: List[Set[Direction]]
    expected_pos: Offset
    expected_state: str
    starting_state: str = "FallState"
    expected_cycles: int = 0
    expected_removed_types: List[str] = field(default_factory=list)
    expected_messages: List[str] = field(default_factory=list)
    expected_object_positions: List[dict] = field(default_factory=list)


SCENARIOS = [
    Scenario(
        name="Corner Collision",
        description="Player moves diagonally into a corner. Should block X and move Y.",
        player_start=Offset(0, 0),
        starting_state="FallState",
        objects_data=[{"type": "Floor", "pos": [1, 1], "size": [4, 1]}],
        timeline=[{"r"}] * 1,
        expected_pos=Offset(1, 0),
        expected_state="PostFallState",
    ),
    Scenario(
        name="Moving Out Of Floor",
        description="Player moves outside floor and fall.",
        player_start=Offset(0, 0),
        starting_state="FallState",
        objects_data=[{"type": "Floor", "pos": [0, 1], "size": [4, 1]}],
        timeline=[{"r"}] * 4,
        expected_pos=Offset(4, 1),
        expected_state="FallState",
    ),
    Scenario(
        name="Spike Fall",
        description="Player falls onto spikes and dies.",
        player_start=Offset(2, 0),
        starting_state="FallState",
        objects_data=[{"type": "Spikes", "pos": [0, 5], "size": [6, 1]}],
        timeline=[set()] * 4,
        expected_pos=Offset(2, 4),
        expected_state="DyingState",
        expected_messages=["HpChange"],
    ),
    Scenario(
        name="Trigger Test",
        description="Player moves through a star. Collected.",
        player_start=Offset(0, 0),
        starting_state="FallState",
        objects_data=[
            {"type": "Star", "pos": [5, 0], "size": [1, 1]},
            {
                "type": "Floor",
                "pos": [0, 1],
                "size": [15, 1],
            },
        ],
        timeline=[{"r"}] * 5,
        expected_pos=Offset(5, 0),
        expected_state="MoveState",
        expected_removed_types=["Star"],
        expected_messages=["PointCollected"],
    ),
    Scenario(
        name="Roof Sticking",
        description="Player jumps into roof and should stay in RoofState.",
        player_start=Offset(0, 4),
        starting_state="StayState",
        objects_data=[
            {"type": "Floor", "pos": [0, 0], "size": [10, 1]},
            {"type": "Floor", "pos": [0, 5], "size": [10, 1]},
        ],
        timeline=[{"u"}] * 10,
        expected_pos=Offset(0, 1),
        expected_state="RoofState",
    ),
    Scenario(
        name="Roof Levitation",
        description="Player moves horizontally outside the roof. Should fall.",
        player_start=Offset(5, 1),
        starting_state="RoofState",
        objects_data=[{"type": "Floor", "pos": [0, 0], "size": [10, 1]}],
        timeline=[{"r"}] * 9,
        expected_pos=Offset(14, 1),
        expected_state="FallState",
    ),
    Scenario(
        name="Jumping over floor",
        description="Player jumps past floor edge. Should not fall through.",
        player_start=Offset(0, 4),
        starting_state="JumpState",
        objects_data=[
            {"type": "Floor", "pos": [5, 1], "size": [5, 1]},
            {"type": "Floor", "pos": [0, 5], "size": [10, 1]},
        ],
        timeline=[{"u", "r"}] * 14,
        expected_pos=Offset(14, 5),
        expected_state="FallState",
    ),
    Scenario(
        name="Wall Press Fall",
        description="Player falls while pressing against a wall. Should slide down.",
        player_start=Offset(0, 0),
        starting_state="FallState",
        objects_data=[{"type": "Floor", "pos": [1, 0], "size": [1, 10]}],
        timeline=[{"r"}] * 5,
        expected_pos=Offset(0, 5),
        expected_state="FallState",
    ),
    Scenario(
        name="Concave Corner",
        description="Jumping into an internal L-corner.",
        player_start=Offset(5, 5),
        starting_state="JumpState",
        objects_data=[
            {"type": "Floor", "pos": [0, 0], "size": [10, 1]},
            {"type": "Floor", "pos": [6, 0], "size": [1, 10]},
        ],
        timeline=[{"u", "r"}] * 4,
        expected_pos=Offset(5, 1),
        expected_state="RoofState",
    ),
    Scenario(
        name="Jumping On Corner",
        description="Jumping into corner",
        player_start=Offset(5, 5),
        starting_state="JumpState",
        objects_data=[
            {"type": "Floor", "pos": [8, 2], "size": [3, 1]},
        ],
        timeline=[{"u", "r"}] * 3,
        expected_pos=Offset(8, 3),
        expected_state="RoofState",
    ),
    Scenario(
        name="Ceiling Spikes",
        description="Jumping up into spikes on ceiling.",
        player_start=Offset(2, 5),
        starting_state="JumpState",
        objects_data=[{"type": "SpikesDown", "pos": [0, 2], "size": [6, 1]}],
        timeline=[set()] * 2,
        expected_pos=Offset(2, 3),
        expected_state="DyingState",
        expected_messages=["HpChange"],
    ),
    Scenario(
        name="Star Proximity",
        description="Moving past a star just out of reach.",
        player_start=Offset(0, 0),
        starting_state="StayState",
        objects_data=[{"type": "Star", "pos": [3, 1], "size": [1, 1]}],
        timeline=[{"r"}] * 10,
        expected_pos=Offset(10, 10),
        expected_state="FallState",
        expected_removed_types=[],
    ),
    Scenario(
        name="Star Proximity",
        description="Moving past a star just out of reach.",
        player_start=Offset(0, 0),
        starting_state="StayState",
        objects_data=[{"type": "Star", "pos": [5, 1], "size": [1, 1]}],
        timeline=[{"r"}] * 10,
        expected_pos=Offset(10, 10),
        expected_state="FallState",
        expected_removed_types=[],
    ),
    Scenario(
        name="Spikes Damage",
        description="Jumping just barely over spikes. Should survive.",
        player_start=Offset(0, 3),
        starting_state="StayState",
        objects_data=[
            {"type": "Spikes", "pos": [5, 4], "size": [4, 1]},
            {"type": "Floor", "pos": [0, 4], "size": [5, 1]},
        ],
        timeline=[{"r"}] * 5,
        expected_pos=Offset(5, 3),
        expected_state="DyingState",
    ),
    Scenario(
        name="Spikes No Damage When Jump Over",
        description="Jumping just barely over spikes. Should survive.",
        player_start=Offset(0, 3),
        starting_state="StayState",
        objects_data=[
            {"type": "Spikes", "pos": [5, 4], "size": [6, 1]},
            {"type": "Floor", "pos": [0, 4], "size": [5, 1]},
        ],
        timeline=[{"u"}] * 3 + [{"u", "r"}] * 5,
        expected_pos=Offset(5, 2),
        expected_state="JumpState",
    ),
    Scenario(
        name="Spikes No Damage When Jump Over One Block To Far",
        description="Jumping just barely over spikes. Should survive.",
        player_start=Offset(0, 3),
        starting_state="StayState",
        objects_data=[
            {"type": "Spikes", "pos": [5, 4], "size": [6, 1]},
            {"type": "Floor", "pos": [0, 4], "size": [5, 1]},
        ],
        timeline=[{"u"}] * 2 + [{"u", "r"}] * 6,
        expected_pos=Offset(6, 2),
        expected_state="JumpState",
    ),
    Scenario(
        name="Spikes Damage When Jump Over Two Blocks To Far",
        description="Jumping just barely over spikes. Should survive.",
        player_start=Offset(0, 3),
        starting_state="StayState",
        objects_data=[
            {"type": "Spikes", "pos": [5, 4], "size": [6, 1]},
            {"type": "Floor", "pos": [0, 4], "size": [5, 1]},
        ],
        timeline=[{"u"}] * 1 + [{"u", "r"}] * 6,
        expected_pos=Offset(6, 3),
        expected_state="DyingState",
    ),
    Scenario(
        name="SpikesDown No Damage When Falling Over One Block To Far",
        description="Falling just barely over spikes. Should survive.",
        player_start=Offset(2, 5),
        starting_state="FallState",
        objects_data=[
            {"type": "SpikesDown", "pos": [4, 5], "size": [6, 1]},
        ],
        timeline=[{"r", "d"}] * 6,
        expected_pos=Offset(8, 11),
        expected_state="FallState",
    ),
    Scenario(
        name="SpikesDown No Damage When Falling Next To Them",
        description="Falling just barely over spikes. Should survive.",
        player_start=Offset(3, 5),
        starting_state="FallState",
        objects_data=[
            {"type": "SpikesDown", "pos": [4, 5], "size": [6, 1]},
        ],
        timeline=[{"r", "d"}] * 6,
        expected_pos=Offset(8, 11),
        expected_state="FallState",
    ),
    Scenario(
        name="SpikesDown No Damage When Jump Over One Blocks To Far",
        description="Jumping just barely over spikes. Should survive.",
        player_start=Offset(2, 6),
        starting_state="JumpState",
        objects_data=[
            {"type": "SpikesDown", "pos": [5, 1], "size": [6, 1]},
        ],
        timeline=[set()] * 7 + [{"r"}] * 6,
        expected_pos=Offset(8, 6),
        expected_state="FallState",
    ),
    Scenario(
        name="SpikesDown Damage When Jump Over Two Blocks To Far",
        description="Jumping just barely over spikes. Should survive.",
        player_start=Offset(2, 6),
        starting_state="JumpState",
        objects_data=[
            {"type": "SpikesDown", "pos": [5, 1], "size": [6, 1]},
        ],
        timeline=[set()] * 6 + [{"r", "d"}] * 6,
        expected_pos=Offset(6, 2),
        expected_state="DyingState",
    ),
    Scenario(
        name="Spikes Side Brush",
        description="Moving horizontally into the side of spikes. Should NOT die.",
        player_start=Offset(0, 4),
        starting_state="StayState",
        objects_data=[
            {"type": "Spikes", "pos": [5, 4], "size": [2, 1]},
            {"type": "Floor", "pos": [0, 5], "size": [10, 1]},
        ],
        timeline=[{"r"}] * 5,
        expected_pos=Offset(4, 4),
        expected_state="StayState",
    ),
    Scenario(
        name="Star Collection Threshold",
        description="Precise check for collection distance. 1 unit away should collect.",
        player_start=Offset(0, 0),
        starting_state="StayState",
        objects_data=[
            {"type": "Star", "pos": [1, 0], "size": [1, 1]},
            {"type": "Floor", "pos": [0, 1], "size": [10, 1]},
        ],
        timeline=[{"r"}] * 1,
        expected_pos=Offset(1, 0),
        expected_state="MoveState",
        expected_removed_types=["Star"],
    ),
    Scenario(
        name="Mid-Jump Star Collection",
        description="Collecting a star during the peak of a jump.",
        player_start=Offset(0, 5),
        starting_state="JumpState",
        objects_data=[{"type": "Star", "pos": [0, 2], "size": [1, 1]}],
        timeline=[set()] * 3,
        expected_pos=Offset(0, 2),
        expected_removed_types=["Star"],
        expected_state="JumpState",
    ),
    Scenario(
        name="Touret Shooting",
        description="Touret shoots laser and damages player (Right).",
        player_start=Offset(5, 3),
        starting_state="StayState",
        objects_data=[
            {
                "type": "Touret",
                "pos": [0, 2],
                "size": [2, 2],
                "shoot_interval": 5,
                "direction": [1, 0],
            },
            {"type": "Floor", "pos": [0, 4], "size": [20, 1]},
        ],
        timeline=[set()] * 20,
        expected_pos=Offset(5, 3),
        expected_state="DyingState",
        expected_messages=["HpChange"],
    ),
    Scenario(
        name="Touret Shooting To High",
        description="Touret shoots laser and misses.",
        player_start=Offset(5, 3),
        starting_state="StayState",
        objects_data=[
            {
                "type": "Touret",
                "pos": [0, 1],
                "size": [2, 2],
                "shoot_interval": 5,
                "direction": [1, 0],
            },
            {"type": "Floor", "pos": [0, 4], "size": [20, 1]},
        ],
        timeline=[set()] * 20,
        expected_pos=Offset(5, 3),
        expected_state="StayState",
        expected_messages=[],
    ),
    Scenario(
        name="Touret Shooting Left",
        description="Touret shoots laser and damages player (Left).",
        player_start=Offset(7, 3),
        starting_state="StayState",
        objects_data=[
            {
                "type": "Touret",
                "pos": [12, 2],
                "size": [2, 2],
                "shoot_interval": 5,
                "direction": [-1, 0],
            },
            {"type": "Floor", "pos": [0, 4], "size": [20, 1]},
        ],
        timeline=[set()] * 20,
        expected_pos=Offset(7, 3),
        expected_state="DyingState",
        expected_messages=["HpChange"],
    ),
    Scenario(
        name="Touret Laser Blocked",
        description="Laser beam should stop at the wall and NOT damage the player behind it.",
        player_start=Offset(10, 3),
        starting_state="StayState",
        objects_data=[
            {
                "type": "Touret",
                "pos": [0, 2],
                "size": [2, 2],
                "shoot_interval": 5,
                "direction": [1, 0],
            },
            {"type": "Floor", "pos": [5, 0], "size": [1, 10]},
            {"type": "Floor", "pos": [0, 4], "size": [20, 1]},
        ],
        timeline=[set()] * 30,
        expected_pos=Offset(10, 3),
        expected_state="StayState",
    ),
    Scenario(
        name="Touret Laser Partially Blocked",
        description="Laser beam passes through a gap in the wall and hits the player.",
        player_start=Offset(10, 3),
        starting_state="StayState",
        objects_data=[
            {
                "type": "Touret",
                "pos": [0, 2],
                "size": [2, 2],
                "shoot_interval": 5,
                "direction": [1, 0],
            },
            {"type": "Floor", "pos": [5, 2], "size": [1, 1]},
            {"type": "Floor", "pos": [5, 4], "size": [1, 1]},
            {"type": "Floor", "pos": [0, 4], "size": [20, 1]},
        ],
        timeline=[set()] * 20,
        expected_pos=Offset(10, 3),
        expected_state="DyingState",
        expected_messages=["HpChange"],
    ),
    Scenario(
        name="Enemy Patrol and Damage",
        description="Enemy moves on floor and hits stationary player.",
        player_start=Offset(5, 3),
        starting_state="StayState",
        objects_data=[
            {"type": "Enemy", "pos": [0, 3], "size": [2, 2], "move_interval": 2},
            {"type": "Floor", "pos": [0, 5], "size": [10, 1]},
        ],
        timeline=[set()] * 20,
        expected_pos=Offset(5, 4),
        expected_state="DyingState",
        expected_messages=["HpChange"],
    ),
    Scenario(
        name="Enemy Edge to Edge Patrol",
        description="Enemy moves from x=0 to x=8 and back to x=0 on a 10-wide floor.",
        player_start=Offset(20, 0),
        starting_state="NoState",
        objects_data=[
            {"type": "Enemy", "pos": [0, 3], "size": [2, 2], "move_interval": 1},
            {"type": "Floor", "pos": [0, 5], "size": [10, 1]},
        ],
        timeline=[set()] * 17,
        expected_pos=Offset(20, 0),
        expected_state="NoState",
        expected_object_positions=[{"type": "Enemy", "pos": Offset(0, 3)}],
    ),
]
