from textual.theme import Theme


# https://vimcolorschemes.com/i/trending
# https://gogh-co.github.io/Gogh/
# https://github.com/seapagan/posting/blob/main/src/posting/themes.py

TOFU_BUILTIN_THEMES = {
    "tofubyte": Theme(
        name="tofubyte",
        primary="#42A5F5",  # Medium blue
        secondary="#A1887F",  # Brownish
        warning="#FFB300",  # More vibrant orange/yellow
        error="#F44336",  # More vibrant red
        success="#4CAF50",  # More vibrant green
        accent="#66CCCC",  # Light blue-green
        background="#1A1A1A",  # Darker charcoal
        surface="#2A2A2A",  # Darker medium charcoal
        panel="#3A3A3A",  # Darker light charcoal
        dark=True,
        variables={"player-color": "#FFFFFF"},  # White
    ),
    "monokai-pro": Theme(
        name="monokai-pro",
        primary="#FFD866",
        secondary="#78DCE8",
        warning="#FC9867",
        error="#FF6188",
        success="#A9DC76",
        accent="#AB9DF2",
        background="#2D2A2E",
        surface="#3A383B",
        panel="#403E41",
        dark=True,
        variables={"player-color": "#AB9DF2"},
    ),
    "nebula": Theme(
        name="nebula",
        primary="#4A9CFF",
        secondary="#66D9EF",
        warning="#FFB454",
        error="#FF5555",
        success="#50FA7B",
        accent="#FF79C6",
        surface="#193549",
        panel="#1F4662",
        background="#0D2137",
        dark=True,
        variables={"player-color": "#FF79C6"},
    ),
    "aurora": Theme(
        name="aurora",
        primary="#45FFB3",
        secondary="#A1FCDF",
        accent="#DF7BFF",
        warning="#FFE156",
        error="#FF6B6B",
        success="#64FFDA",
        background="#0A1A2F",
        surface="#142942",
        panel="#1E3655",
        dark=True,
        variables={"player-color": "#DF7BFF"},
    ),
    "cobalt": Theme(
        name="cobalt",
        primary="#334D5C",
        secondary="#66B2FF",
        warning="#FFAA22",
        error="#E63946",
        success="#4CAF50",
        accent="#D94E64",
        surface="#27343B",
        panel="#2D3E46",
        background="#1F262A",
        dark=True,
        variables={"player-color": "#D94E64"},
    ),
    "synthwave": Theme(
        name="synthwave",
        primary="#FF006E",
        secondary="#8338EC",
        warning="#FFBE0B",
        error="#FB5607",
        success="#06FFA5",
        accent="#3A86FF",
        background="#0F0A19",
        surface="#1A0F26",
        panel="#251833",
        dark=True,
        variables={"player-color": "#3A86FF"},
    ),
    "nordic-frost": Theme(
        name="nordic-frost",
        primary="#88C0D0",
        secondary="#81A1C1",
        warning="#EBCB8B",
        error="#BF616A",
        success="#A3BE8C",
        accent="#5E81AC",
        background="#2E3440",
        surface="#3B4252",
        panel="#434C5E",
        dark=True,
        variables={"player-color": "#5E81AC"},
    ),
    "everforest-dark": Theme(
        name="everforest-dark",
        primary="#A7C080",
        secondary="#D3C6AA",
        warning="#DBBC7F",
        error="#E67E80",
        success="#83C092",
        accent="#7FBBB3",
        background="#2D353B",
        surface="#343F44",
        panel="#3D484D",
        dark=True,
        variables={"player-color": "#7FBBB3"},
    ),
    "rose-pine-moon": Theme(
        name="rose-pine-moon",
        primary="#EA9D34",
        secondary="#9CCFD8",
        warning="#F6C177",
        error="#EB6F92",
        success="#31748F",
        accent="#C4A7E7",
        background="#232136",
        surface="#2A273F",
        panel="#393552",
        dark=True,
        variables={"player-color": "#C4A7E7"},
    ),
    "cyberpunk-2077": Theme(
        name="cyberpunk-2077",
        primary="#FDF001",
        secondary="#00F0FF",
        warning="#FFB800",
        error="#FF003C",
        success="#39FF14",
        accent="#FF00FF",
        background="#000000",
        surface="#1A1A1A",
        panel="#262626",
        dark=True,
        variables={"player-color": "#FDF001"},
    ),
    "dracula-pro-blade": Theme(
        name="dracula-pro-blade",
        primary="#50FA7B",
        secondary="#8BE9FD",
        warning="#F1FA8C",
        error="#FF5555",
        success="#5AF78E",
        accent="#BD93F9",
        background="#1D2125",
        surface="#24292E",
        panel="#2F363D",
        dark=True,
        variables={"player-color": "#BD93F9"},
    ),
    "gruvbox-retro": Theme(
        name="gruvbox-retro",
        primary="#FABD2F",
        secondary="#83A598",
        warning="#FE8019",
        error="#FB4934",
        success="#B8BB26",
        accent="#D3869B",
        background="#282828",
        surface="#32302F",
        panel="#3C3836",
        dark=True,
        variables={"player-color": "#D3869B"},
    ),
    "tokyo-night-storm": Theme(
        name="tokyo-night-storm",
        primary="#7AA2F7",
        secondary="#7DCFFF",
        warning="#E0AF68",
        error="#F7768E",
        success="#9ECE6A",
        accent="#BB9AF7",
        background="#24283B",
        surface="#2F354B",
        panel="#3B4261",
        dark=True,
        variables={"player-color": "#BB9AF7"},
    ),
    "deep-sea": Theme(
        name="deep-sea",
        primary="#00D2FF",
        secondary="#3A7BD5",
        warning="#FFD166",
        error="#EF476F",
        success="#06D6A0",
        accent="#118AB2",
        background="#001219",
        surface="#001B24",
        panel="#073B4C",
        dark=True,
        variables={"player-color": "#118AB2"},
    ),
    "volcanic": Theme(
        name="volcanic",
        primary="#FF4D00",
        secondary="#9D0208",
        warning="#FFB700",
        error="#D00000",
        success="#52B788",
        accent="#E85D04",
        background="#0B090A",
        surface="#161A1D",
        panel="#22272B",
        dark=True,
        variables={"player-color": "#E85D04"},
    ),
    "amethyst-smoke": Theme(
        name="amethyst-smoke",
        primary="#B8B8FF",
        secondary="#9381FF",
        warning="#FFD6FF",
        error="#E88873",
        success="#B8E1FF",
        accent="#F8F7FF",
        background="#1F2024",
        surface="#2E3035",
        panel="#3D3F46",
        dark=True,
        variables={"player-color": "#F8F7FF"},
    ),
    "slate-honey": Theme(
        name="slate-honey",
        primary="#FFB703",
        secondary="#FB8500",
        warning="#8ECAE6",
        error="#D00000",
        success="#219EBC",
        accent="#023047",
        background="#0A1114",
        surface="#141E24",
        panel="#1D2A33",
        dark=True,
        variables={"player-color": "#FFB703"},
    ),
    "outrun-grid": Theme(
        name="outrun-grid",
        primary="#FF00FF",
        secondary="#00FFFF",
        warning="#F7FF00",
        error="#FF4500",
        success="#39FF14",
        accent="#BD00FF",
        background="#0D0221",
        surface="#190E4F",
        panel="#261447",
        dark=True,
        variables={"player-color": "#BD00FF"},
    ),
    "minimal-ink": Theme(
        name="minimal-ink",
        primary="#E0E0E0",
        secondary="#A0A0A0",
        warning="#F5F5F5",
        error="#FF0000",
        success="#FFFFFF",
        accent="#404040",
        background="#000000",
        surface="#111111",
        panel="#222222",
        dark=True,
        variables={"player-color": "#404040"},
    ),
    "imperial-blue": Theme(
        name="imperial-blue",
        primary="#FFD700",
        secondary="#FFFFFF",
        warning="#FFB000",
        error="#FF4B2B",
        success="#00FF87",
        accent="#0056B3",
        background="#000B18",
        surface="#001F3D",
        panel="#002E5C",
        dark=True,
        variables={"player-color": "#0056B3"},
    ),
}
